/* This file is automatically generated by ABP framework to use MVC Controllers from javascript. */


// module yarpManagement

(function(){

  // controller taitans.yarpManagement.proxyConfig

  (function(){

    abp.utils.createNamespace(window, 'taitans.yarpManagement.proxyConfig');

    taitans.yarpManagement.proxyConfig.getList = function(input, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/yarp-management/proxy-config' + abp.utils.buildQueryString([{ name: 'filter', value: input.filter }, { name: 'sorting', value: input.sorting }, { name: 'skipCount', value: input.skipCount }, { name: 'maxResultCount', value: input.maxResultCount }]) + '',
        type: 'GET'
      }, ajaxParams));
    };

    taitans.yarpManagement.proxyConfig.getHistoryList = function(input, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/yarp-management/proxy-config/historys' + abp.utils.buildQueryString([{ name: 'name', value: input.name }, { name: 'sorting', value: input.sorting }, { name: 'skipCount', value: input.skipCount }, { name: 'maxResultCount', value: input.maxResultCount }]) + '',
        type: 'GET'
      }, ajaxParams));
    };

    taitans.yarpManagement.proxyConfig.rollBack = function(id, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/yarp-management/proxy-config/' + id + '/roll-back',
        type: 'PUT',
        dataType: null
      }, ajaxParams));
    };

    taitans.yarpManagement.proxyConfig.create = function(input, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/yarp-management/proxy-config',
        type: 'POST',
        dataType: null,
        data: JSON.stringify(input)
      }, ajaxParams));
    };

    taitans.yarpManagement.proxyConfig.reload = function(id, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/yarp-management/proxy-config/' + id + '/reload',
        type: 'PUT',
        dataType: null
      }, ajaxParams));
    };

    taitans.yarpManagement.proxyConfig.get = function(id, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/yarp-management/proxy-config/' + id + '',
        type: 'GET'
      }, ajaxParams));
    };

  })();

})();


