name: .NET Core

on: 
  push:
    branches: ["*"]
    tags: ['*']

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Restore
      run: dotnet restore Taitans.YarpManagement.sln -nowarn:msb3202,nu1503
      
    - name: Restore
      run: dotnet build Taitans.YarpManagement.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test Taitans.YarpManagement.sln --configuration Release